# Basic
# --------------------------------------
title: 沉默的大多数
subtitle: 个人站
description: 为你，千千万万遍。
avatarTitle: AhHui                    # 头像里面的标题
avatarDesc: 2025 / 勇敢                # 头像里面的描述
url: "https://ahhuipt.github.io/"
baseurl: ""
enableToc: true       # 博客是否自动生成目录
permalink: /:year/:month/:title/

# Format
highlighter: rouge

# 主题颜色
textColor: "#FF0000"
cover_color: clear  # supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.


# Navigation menu
# --------------------------------------
# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 技术支持, description: support, url: '/support'}      
    - {title: 关于我, description: about, url: '/about'}   


# Social
# --------------------------------------
social:
    weibo: 6666454445
    github: ahhuipt
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    twitter: ahuipt
    mail: 2022226041@chd.edu.cn

# Comment
# --------------------------------------
comment:
    # disqus，国外比较火的评论系统，但在国内墙了
    # disqus用户名，登录http://disqus.com/ 官网申请(不过貌似这个目前国内又用不了了)
    disqus: yinhuiguo

    # Support for LiveRe comments system.
    # You can get your uid from https://www.livere.com/login_form (General web site)
    # livere_uid: MTAyMC80MzQ5OS8yMDAzOQ==    # Livere 是一个支持中文的评论系统，适合国内用户。

    # uyan: 2143225  # 有言id,登录有言官网申请     # 已停止服务

# Analysis
# --------------------------------------
# Baidu Analytics
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 82a023515c1f80d3aba104b74def44c3
# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-84134159-3  
    host: auto  


# 启用的 Jekyll 插件  
# --------------------------------------
# Pagination
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# 分页设置
paginate: 20
paginate_path: "/page/:num/"


# ==================================================
#                    其他说明
# ==================================================
# 博客模板来源：https://github.com/leopardpan/leopardpan.github.io
# 使用本模板请保留 attribution 或注明出处