name: Algolia Indexing

on:
  push:
    branches: [ main ]
  # 添加 schedule 触发器
  schedule:
    - cron: "0 1 * * *"  # 每天 UTC 时间 01:00 运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build and push to Algolia
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_TOKEN }}
        run: bundle exec jekyll algolia